name = "nav-page-worker"
main = "worker/index.js"  # Add worker/ prefix
compatibility_date = "2024-01-01"

# KV Namespace binding
[[kv_namespaces]]
binding = "NAV_TILES"
id = "619d2c0e9bc9483183dd7efe541726d9"  # Replace with your actual KV namespace ID

# Routes (optional - can also be configured in Cloudflare dashboard)
# route = "https://api.yourdomain.com/*"

# Development settings
[dev]
port = 8787
local_protocol = "http"

# Environment variables (optional)
[vars]
# Add any environment variables here if needed
